openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/chatmate/api/document/:
    get:
      operationId: listDocuments
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
    post:
      operationId: createDocuments
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
  /api/chatmate/api/document/{id}/:
    get:
      operationId: retrieveDocuments
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this documents.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
    put:
      operationId: updateDocuments
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this documents.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateDocuments
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this documents.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyDocuments
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this documents.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/chatmate/api/query/:
    get:
      operationId: listQuerys
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    post:
      operationId: createQuery
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
  /api/chatmate/api/query/{id}/:
    get:
      operationId: retrieveQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    put:
      operationId: updateQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/chatmate/api/document/upload_file/:
    post:
      operationId: uploadFileDocuments
      description: ''
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Document'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
  /api/chatmate/api/query/process_chat/:
    post:
      operationId: processChatQuery
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
components:
  schemas:
    Document:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        file:
          type: string
          format: binary
          nullable: true
        link:
          type: string
          format: uri
          nullable: true
          maxLength: 200
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4]\\\
            d|1\\d?\\d?|[1-9]\\d?)(?:\\.(?:0|25[0-5]|2[0-4]\\d|1\\d?\\d?|[1-9]\\d?)){3}|\\\
            [[0-9a-f:.]+\\]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1\
            -\uFFFF0-9])?(?:\\.(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1\
            -\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost))(?::\\d{2,5})?(?:[/?#][^\\\
            s]*)?\\z"
        uploaded_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - title
    Query:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        query_text:
          type: string
        response_text:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - query_text
      - response_text
