openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/chatmate/api/document/:
    get:
      operationId: listDocuments
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
    post:
      operationId: createDocuments
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
  /api/chatmate/api/document/{id}/:
    get:
      operationId: retrieveDocuments
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this documents.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
    put:
      operationId: updateDocuments
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this documents.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateDocuments
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this documents.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyDocuments
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this documents.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/chatmate/api/query/:
    get:
      operationId: listQuerys
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    post:
      operationId: createQuery
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
  /api/chatmate/api/query/{id}/:
    get:
      operationId: retrieveQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    put:
      operationId: updateQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/chatmate/api/query/{id}/get_queries_by_room_id/:
    get:
      operationId: getQueriesByRoomIdQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
  /api/chatmate/api/combinedchunk/:
    get:
      operationId: listCombinedChunks
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CombinedChunk'
          description: ''
      tags:
      - api
    post:
      operationId: createCombinedChunk
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CombinedChunk'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombinedChunk'
          description: ''
      tags:
      - api
  /api/chatmate/api/combinedchunk/{id}/:
    get:
      operationId: retrieveCombinedChunk
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this combined chunk.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombinedChunk'
          description: ''
      tags:
      - api
    put:
      operationId: updateCombinedChunk
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this combined chunk.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CombinedChunk'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombinedChunk'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateCombinedChunk
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this combined chunk.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CombinedChunk'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombinedChunk'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyCombinedChunk
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this combined chunk.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/chatmate/api/rooms/:
    get:
      operationId: listRooms
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rooms'
          description: ''
      tags:
      - api
    post:
      operationId: createRooms
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rooms'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rooms'
          description: ''
      tags:
      - api
  /api/chatmate/api/rooms/{id}/:
    get:
      operationId: retrieveRooms
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique value identifying this rooms.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rooms'
          description: ''
      tags:
      - api
    put:
      operationId: updateRooms
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique value identifying this rooms.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rooms'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rooms'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateRooms
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique value identifying this rooms.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rooms'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rooms'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyRooms
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique value identifying this rooms.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/chatmate/api/document/upload_file/:
    post:
      operationId: uploadFileDocuments
      description: ''
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Document'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
  /api/chatmate/api/query/process_chat/:
    post:
      operationId: processChatQuery
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
  /api/chatmate/api/document/{id}/update_document/:
    put:
      operationId: updateDocumentDocuments
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this documents.
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Document'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
      tags:
      - api
  /api/chatmate/api/query/{id}/edit_query/:
    put:
      operationId: editQueryQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
  /api/chatmate/api/document/delete_all_documents/:
    delete:
      operationId: deleteAllDocumentsDocuments
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/chatmate/api/document/{id}/delete_document/:
    delete:
      operationId: deleteDocumentDocuments
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this documents.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Document:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        file:
          type: string
          format: binary
          nullable: true
        link:
          type: string
          format: uri
          nullable: true
          maxLength: 200
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4]\\\
            d|1\\d?\\d?|[1-9]\\d?)(?:\\.(?:0|25[0-5]|2[0-4]\\d|1\\d?\\d?|[1-9]\\d?)){3}|\\\
            [[0-9a-f:.]+\\]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1\
            -\uFFFF0-9])?(?:\\.(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1\
            -\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost))(?::\\d{2,5})?(?:[/?#][^\\\
            s]*)?\\z"
        uploaded_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - title
    Query:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        query_text:
          type: string
        response_text:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        room:
          type: string
      required:
      - query_text
      - response_text
      - room
    CombinedChunk:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        chunks:
          type: object
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    Rooms:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
          maxLength: 255
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - name
