# Generated by Django 3.2.10 on 2024-07-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatmate', '0002_auto_20240719_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
