# Generated by Django 3.2.10 on 2024-07-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatmate', '0003_auto_20240719_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Documents',
        ),
    ]
