# Generated by Django 3.2.10 on 2024-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatmate', '0005_combinedchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedchunk',
            name='chunks',
            field=models.JSONField(default=list),
        ),
    ]
